### ISSUE TITLE
Add `--with-profile` to CLI

### ISSUE THREAD

**Issue by albireox** [sdss/lvmcryo#7]
When we run one of the LN2 fill cronjobs we set a lot of options via environment variables when calling the CLI, for example

```yaml
env:
  - name: LVMCRYO_CONFIG_FILE
    value: /home/sdss5/config/software/lvmcryo/lvmcryo.yaml
  - name: LVMOPSTOOLS_CONFIG_FILE
    value: /home/sdss5/config/software/lvmopstools/lvmopstools.yaml
  - name: LVMCRYO_INTERACTIVE
    value: 'no'
  - name: LVMCRYO_DEBUG
    value: '1'
  - name: LVMCRYO_NOTIFY
    value: '1'
  - name: LVMCRYO_WRITE_LOG
    value: '1'
  - name: LVMCRYO_WRITE_JSON
    value: '1'
  - name: LVMCRYO_WRITE_DATA
    value: '1'
  - name: LVMCRYO_EMAIL_LEVEL
    value: info
  - name: LVMCRYO_DATA_EXTRA_TIME
    value: '120'
command:
  - /bin/bash
  - -c
  - lvmcryo ln2 --clear-lock
```

Alternatively this would require a very long `lvmcryo ln2` call with lots of flags. Instead we could have something like

```
lvmcryo ln2 --with-profile cronjob-fill
```

and then in the configuration file we define the values of the parameters to pass to `Config`. If a flag or envvar is explicitly passed, that overrides the profile default.
